Repository afterclass-io/afterclass.io, pull requests merged in 2024-06, with the labels that each got.

#155 feat: add favicon and og image
  public/favicon.ico
  src/app/favicon.ico
  src/app/opengraph-image.alt.txt
  src/app/opengraph-image.png
  src/app/twitter-image.alt.txt
  src/app/twitter-image.png
  src/middleware.ts
Labels: enhancement

#154 docs: github community standard
  .git-blame-ignore-revs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/assets/afterclass-with-name.png
  .github/assets/afterclass-with-name.svg
  .github/assets/afterclass-without-name.png
  .github/assets/afterclass-without-name.svg
  .github/assets/screenshot-course.png
  .github/workflows/promote-prod.yml
  .storybook/README.md
  ARCHITECTURE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEPLOYMENT.md
  DEVELOPMENT.md
  LICENSE
  PHILOSOPHY.md
  README.md
  docs/README.md
  docs/decisions/0001-magic-link-for-auth.md
  docs/decisions/TEMPLATE.md
  prisma/README.md
  src/common/constants/README.md
  src/common/functions/README.md
  src/common/hooks/README.md
  src/common/providers/README.md
  src/common/tools/README.md
  src/common/types/README.md
  src/modules/README.md
  src/server/README.md
Labels: documentation

#152 feat(ui): search ui flow
  src/app/(school)/search/page.tsx
  src/common/components/FilterToggleSection/FilterToggleSectionItem/FilterToggleSectionItem.tsx
  src/common/components/PageTitle/PageTitle.tsx
  src/common/components/SearchCmdk/SearchCmdk.theme.ts
  src/common/components/SearchCmdk/SearchCmdk.tsx
  src/common/components/SearchCmdk/index.ts
  src/common/components/SearchResult/SearchResult.theme.ts
  src/common/components/SearchResult/SearchResult.tsx
  src/common/components/SearchResult/SearchResultFilter/SearchResultFilter.tsx
  src/common/components/SearchResult/SearchResultFilter/index.ts
  src/common/components/SearchResult/SearchResultItem/SearchResultItem.tsx
  src/common/components/SearchResult/SearchResultItem/index.ts
  src/common/components/SearchResult/SearchResultTitle/SearchResultTitle.tsx
  src/common/components/SearchResult/SearchResultTitle/index.ts
  src/common/components/SearchResult/index.ts
  src/common/components/Sidebar/Sidebar.tsx
  src/common/components/Tag/Tag.tsx
  src/common/components/ToggleGroup/index.ts
  src/middleware.ts
Labels: enhancement

#143 Add Posthog analytics
  .env.example
  package.json
  src/app/layout.tsx
  src/common/providers/analytics/PostHogPageView.tsx
  src/common/providers/analytics/providers.tsx
  src/env.mjs
  yarn.lock
Labels: enhancement

#176 update header to use login button
  src/app/(school)/layout.tsx
Labels: UI

#177 refactor: hide see more reviews
  src/common/components/ReviewItem/ReviewItem.tsx
Labels: refactoring
