Repository afterclass-io/afterclass.io, pull requests merged in 2025-01, with the labels that each got.

#387 feat(ui): add Google Auth as sign in option
  .env.example
  bun.lock
  src/common/components/CoreLayout/CoreLayoutHeader/CoreLayoutHeader.tsx
  src/modules/auth/components/GoogleSignInButton.tsx
  src/modules/auth/components/LoginForm.tsx
  src/server/auth/config.ts
Labels: enhancement

#389 fix: auth display error on failure & session user to match db user on google auth
  src/env.ts
  src/modules/auth/components/GoogleSignInButton.tsx
  src/modules/auth/components/LoginForm.tsx
  src/server/auth/config.ts
Labels: bug

#396 chore(deps): upgrade prisma to v6
  bun.lock
  package.json
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  sentry.server.config.ts
Labels: blocked
